### ISSUE TITLE
15215 and 22407 Autonomous 

### ISSUE THREAD

**Issue by lapadapdap** [holo911/BunyipsFTC#49]
**15215**
- [x] RoadRunner general reliability
- [x] Backboard routes
- [x] Pixel backboard placement
- [x] Parking (left + right opmodes)
- [x] Spike Mark detection
- [x] Spike Mark placing

**22407**
- [x] RoadRunner general reliability
- [x] Backboard routes
- [x] Pixel backboard placement
- [x] Parking (left + right opmodes)
- [ ] ~~Spike Mark detection~~
- [ ] ~~Spike Mark placing~~

**Comment by bubner** [comment]
Left Red Park is working, need to integrate the other three and get Vision interoping with RoadRunner ASAP.

**Comment by lapadapdap** [comment]
Very late update, but Wheatley's parking auto are all completed.

**Comment by bubner** [comment]
We have officially done the bare minimum, yay

**Comment by lapadapdap** [comment]
> We have officially done the bare minimum, yay

just let me be happy :((

**Comment by bubner** [comment]
Glados park does not exist, I can't say anything
